local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://saloonanatolia.netlify.app"
display_url: "https://saloonanatolia.netlify.app"
logo_url: "https://saloonanatolia.netlify.app/android-chrome-512x512.png"
locale: "it"

collections:
  - name: "menu"
    label: "Menu"
    files:
      - label: "Menu"
        name: "menu"
        file: "src/data/menu.json"
        editor:
          preview: false
        fields:
          - label: "Menu"
            name: "menu"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Nome", name: "name", widget: "string"}
              - { label: "Gruppo", name: "group", widget: "string"}
              - { label: "Descrizione", name: "description", widget: "text", required: false}
              - { label: "Colonna", name: "column", widget: "number", default: 1, min: 1, max: 2, step: 1}
              - label: "Contenuto"
                name: "content"
                widget: "list"
                allow_add: true
                fields:
                  - {label: "Nome", name: "name", widget: "string"}
                  - {label: "Special", name: "special", widget: "boolean", default: false}
                  - { label: "Descrizione", name: "description", widget: "text", required: false}
  - name: "reviews"
    label: "Recensioni"
    files:
      - label: "Recensioni"
        name: "reviews"
        file: "src/data/reviews.json"
        editor:
          preview: false
        fields:
          - { label: "Voto medio", name: "avg_rating", widget: "number", value_type: "float", default: 0, min: 0, max: 10, step: 0.1}
          - { label: "Numero recensioni", name: "ctr_reviews", widget: "number", default: 0, step: 1}
          - label: "Recensioni"
            name: "reviews"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Nome", name: "name", widget: "string"}
              - { label: "URL", name: "url", widget: "string"}
              - { label: "Voto", name: "rating", widget: "number", value_type: "float", default: 0, min: 0, max: 10, step: 0.1, required: false}
              - { label: "Contenuto", name: "content", widget: "text"}
  - name: "settings"
    label: "Impostazioni"
    files:
      - name: "site_config"
        label: "Configurazione Sito"
        file: "src/site_config.json"
        editor:
          preview: false
        fields:
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Sottotitolo", name: "subtitle", widget: "string" }
          - { label: "Motto", name: "motto", widget: "string", required: false}
          - { label: "Descrizione", name: "description", widget: "text"}
          - { label: "Telefono", name: "phone", widget: "string"}
          - { label: "Mail", name: "email", widget: "string", required: false}
          - { label: "Deliveroo", name: "deliveroo", widget: "string", required: false}
          - { label: "JustEat", name: "justeat", widget: "string", required: false}
          - { label: "Maps Link", name: "maps_link", widget: "string"}

