local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://saloonanatolia.netlify.app"
display_url: "https://saloonanatolia.netlify.app"
logo_url: "https://saloonanatolia.netlify.app/favicon.svg"
locale: "it"

collections:
  - name: "menu"
    label: "Menu"
    files:
      - label: "Menu"
        name: "menu"
        file: "src/data/menu.json"
        editor:
          preview: false
        fields:
          - label: "Menu"
            name: "menu"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Nome", name: "name", widget: "string"}
              - { label: "Descrizione", name: "description", widget: "text", required: false}
              - { label: "Colonna", name: "column", widget: "number", default: 1, min: 1, max: 2, step: 1}
              - label: "Contenuto"
                name: "content"
                widget: "list"
                allow_add: true
                fields:
                  - {label: "Nome", name: "name", widget: "string"}
                  - { label: "Descrizione", name: "description", widget: "text", required: false}
  - name: "settings"
    label: "Impostazioni"
    files:
      - name: "site_config"
        label: "Configurazione Sito"
        file: "src/site_config.json"
        editor:
          preview: false
        fields:
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Sottotitolo", name: "subtitle", widget: "string" }
          - { label: "Motto", name: "motto", widget: "string"}
          - { label: "Descrizione", name: "description", widget: "text"}
          - { label: "CTA", name: "cta", widget: "string" }